# Generated by Django 5.2.7 on 2025-11-01 10:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BottlePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('alt_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=10)),
                ('owner_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('card', models.CharField(blank=True, max_length=50, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=15, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, max_length=20, null=True)),
                ('mmid', models.CharField(blank=True, max_length=20, null=True)),
                ('vpa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Virtual Payment Address')),
                ('upi_number', models.CharField(blank=True, max_length=15, null=True)),
                ('upi_qr', models.ImageField(blank=True, null=True, upload_to='upi_qr/')),
                ('hsn_code', models.CharField(blank=True, default='28044090', max_length=20, null=True)),
                ('cum_value', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=6)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_bottles', models.IntegerField()),
                ('returned_bottles', models.IntegerField()),
                ('pending_bottles', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_bottle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('bill_type', models.CharField(choices=[('auto', 'Automated'), ('custom', 'Custom'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('manual_bill', models.BooleanField(default=False)),
                ('manual_gas_type', models.CharField(blank=True, max_length=100, null=True)),
                ('manual_challan_number', models.IntegerField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_paid', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottle_MGMT.client')),
            ],
            options={
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('delivered', 'Delivered')], default='in_stock', max_length=10)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bottle_MGMT.bottlecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ManualBillRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gas_type', models.CharField(max_length=100)),
                ('challan_no', models.IntegerField(blank=True, null=True)),
                ('hsn', models.CharField(blank=True, default='28044090', max_length=20, null=True)),
                ('qty', models.IntegerField()),
                ('cum', models.DecimalField(decimal_places=2, default=Decimal('7.00'), max_digits=6)),
                ('total_qty', models.IntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_rows', to='bottle_MGMT.bill')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the transaction')),
                ('custom_date', models.DateTimeField(blank=True, help_text='Optional custom date for the transaction. If not provided, current date/time will be used.', null=True)),
                ('transaction_type', models.CharField(choices=[('delivered', 'Delivered'), ('returned', 'Returned')], max_length=10)),
                ('billed', models.BooleanField(default=False)),
                ('challan_number', models.IntegerField(blank=True, null=True)),
                ('bottles', models.ManyToManyField(to='bottle_MGMT.bottle')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottle_MGMT.client')),
                ('delivered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bottle_photos/')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bottle_MGMT.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='BillTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_transactions', to='bottle_MGMT.bill')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_transactions', to='bottle_MGMT.transaction')),
            ],
            options={
                'unique_together': {('bill', 'transaction')},
            },
        ),
    ]
