# Generated by Django 5.0.1 on 2025-07-17 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='in_stock', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='bottle_photos/')),
                ('transaction_type', models.CharField(choices=[('delivered', 'Delivered'), ('returned', 'Returned')], max_length=10)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottle_MGMT.bottle')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottle_MGMT.client')),
                ('delivered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
