# Generated by Django 5.0.1 on 2025-07-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
