# Generated by Django 5.0.1 on 2025-07-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0002_alter_bottle_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottlePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
            ],
        ),
    ]
