# Generated by Django 5.0.1 on 2025-07-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0004_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
