# Generated by Django 5.0.1 on 2025-07-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0006_bill_paid_bill_paid_by_bill_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('auto', 'Automatic'), ('custom', 'Custom')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='custom_billed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomBillTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_transactions', to='bottle_MGMT.bill')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottle_MGMT.transaction')),
            ],
            options={
                'unique_together': {('bill', 'transaction')},
            },
        ),
    ]
