# Generated by Django 5.0.1 on 2025-07-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0007_bill_bill_type_bill_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='custom_billed',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('auto', 'Automated'), ('custom', 'Custom')], default='auto', max_length=10),
        ),
        migrations.CreateModel(
            name='BillTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_transactions', to='bottle_MGMT.bill')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_transactions', to='bottle_MGMT.transaction')),
            ],
            options={
                'unique_together': {('bill', 'transaction')},
            },
        ),
        migrations.DeleteModel(
            name='CustomBillTransaction',
        ),
    ]
