# Generated by Django 5.2.4 on 2025-07-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0008_remove_transaction_custom_billed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='alt_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
