# Generated by Django 5.2.4 on 2025-08-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0010_client_bank_account_client_card_client_owner_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bottle',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bottles',
            field=models.ManyToManyField(to='bottle_MGMT.bottle'),
        ),
    ]
