# Generated by Django 5.2.4 on 2025-08-03 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0011_remove_transaction_bottle_transaction_bottles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='photo',
        ),
        migrations.CreateModel(
            name='TransactionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bottle_photos/')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bottle_MGMT.transaction')),
            ],
        ),
    ]
