# Generated by Django 5.2.4 on 2025-08-03 07:40

import django.db.models.deletion
from django.db import migrations, models

def create_default_category_and_assign(apps, schema_editor):
    BottleCategory = apps.get_model('bottle_MGMT', 'BottleCategory')
    Bottle = apps.get_model('bottle_MGMT', 'Bottle')
    # Create default category
    oxygen_category, created = BottleCategory.objects.get_or_create(id=1, defaults={'name': 'Oxygen'})
    # Assign all bottles to default category
    Bottle.objects.filter(category__isnull=True).update(category=oxygen_category)


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0012_remove_transaction_photo_transactionphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bottle',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bottle_MGMT.bottlecategory'),
        ),
        migrations.RunPython(create_default_category_and_assign),
    ]
