# Generated by Django 5.2.4 on 2025-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0014_bill_discount_amount_bill_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='account_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ifsc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mmid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='upi_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='upi_qr',
            field=models.ImageField(blank=True, null=True, upload_to='upi_qr/'),
        ),
        migrations.AddField(
            model_name='client',
            name='vpa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Virtual Payment Address'),
        ),
    ]
