# Generated by Django 5.0.1 on 2025-08-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0015_client_account_holder_client_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='custom_date',
            field=models.DateTimeField(blank=True, help_text='Optional custom date for the transaction. If not provided, current date/time will be used.', null=True),
        ),
    ]
