# Generated by Django 5.0.1 on 2025-08-31 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_MGMT', '0016_transaction_custom_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the transaction'),
        ),
    ]
